services:
  rabbitmq:
    image: masstransit/rabbitmq:3.11.18
    tty: true
    hostname: rabbitmq
    container_name: rabbitmq-masstransit
    restart: always
    env_file:
      - .env
    volumes:
      - rabbitmq-masstransit_db:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
    command: >
      sh -c "
        rabbitmq-plugins enable --offline rabbitmq_mqtt &&
        rabbitmq-server
      "

volumes:
  rabbitmq-masstransit_db: