services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:100 # should be owner of volumes
    ports:
      - "9090:4533"
    restart: unless-stopped
    volumes:
      - "navidrome-data:/data"
      - "/path/to/music:/music:ro"

volumes:
   navidrome-data: