version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data/
    ports:
      - 8080:80
    env_file:
      - .env

volumes:
  vaultwarden_data: